spring:
  application:
    name: library-service

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: create-drop

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}