spring:
  application:
    name: config-server

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kadirsametseki/kitaplik-online-microservice.git
          search-paths: config

server:
  port: 8889

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    root: debug